[package]
name = "docker-exporter"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.7.9"
bollard = "0.18.1"
futures = "0.3.31"
prometheus-client = "0.22.3"
tokio = { version = "1.42.0", features = ["full"] }
